version: "3"

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes

    broker01:
        image: 'bitnami/kafka:latest'
        ports:
          - '29092:29092'
        environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
          - KAFKA_CFG_LISTENERS=CLIENT://broker01:9092,EXTERNAL://broker01:29092
          - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker01:9092,EXTERNAL://localhost:29092
          - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper

    connect:
        image: debezium/connect:2.0
        ports:
         - 8083:8083
        links:
         - broker01
        environment:
         - BOOTSTRAP_SERVERS=broker01:9092
         - GROUP_ID=1
         - CONFIG_STORAGE_TOPIC=my_connect_configs
         - OFFSET_STORAGE_TOPIC=my_connect_offsets
         - STATUS_STORAGE_TOPIC=my_source_connect_statuses

    ksqldb-server:
        image: confluentinc/ksqldb-server:latest
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
          - broker01
          - connect
        ports:
          - "8088:8088"
        environment:
          KSQL_CONFIG_DIR: "/etc/ksql"
          KSQL_BOOTSTRAP_SERVERS: "broker01:9092"
          KSQL_HOST_NAME: ksqldb-server      
          KSQL_KSQL_CONNECT_URL: "http://connect:8083"
          KSQL_LISTENERS: "http://0.0.0.0:8088"
          KSQL_CACHE_MAX_BYTES_BUFFERING: 0

    control-center:
        image: confluentinc/cp-enterprise-control-center:7.3.1
        hostname: control-center
        container_name: control-center
        depends_on:
          - broker01
        ports:
          - "9021:9021"
        environment:
          CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker01:9092'
          #CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
          CONTROL_CENTER_REPLICATION_FACTOR: 1
          CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
          CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
          CONFLUENT_METRICS_TOPIC_REPLICATION: 1
          PORT: 9021 